language: node_js
cache:
  directories:
    - node_modules
    # cache NPM modules
    - ~/.npm
    # cache Cypress binary
    - ~/.cache
notifications:
  email: true
node_js:
  - '10'
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default,
      # so we need to install it ourselves
      - libgconf-2-4
before_script:
  - npm ci
script:
  - npm test
  # - npm run clean
  # ignore result because is failing on purpose
  # - npm run cy:run || true
  # - npm run verify-failed-json
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
